### ISSUE TITLE
[EPIC 04] - Raterunden

### ISSUE THREAD

**Issue by Thunder1702** [SE2-Busfahrer-SS20/SE2-Busfahrer-SS20#12]
Es sollen alle 4 Raterunden implementiert und voll funktionsfähig seien.

- [x] #19 STORY 1 - Raterunde 1 implementieren
- [x] #20 STORY 2 - Raterunde 2: Rang höher/niedriger
- [x] #22 STORY 3 - Raterunde 3: innerhalb/außerhalb
- [x] #23 STORY 4 - Raterunde 4: Farbe
