### ISSUE TITLE
[EPIC 02] - Jeder Spieler hat seine 4 Karten verdeckt vor sich.

### ISSUE THREAD

**Issue by Thunder1702** [SE2-Busfahrer-SS20/SE2-Busfahrer-SS20#8]
Jeder Spieler hat seine 4 Spielkarten verdeckt vor sich und kann mit der Raterunde beginnen.

- [x] #14 STORY 1 - Erstellen der Screens
- [x] #15 STORY 2 - Karten erstellen 
- [x] #16 STORY 3 - Karten mischen
- [x] #17 STORY 4 - Karten austeilen
- [ ] #18 STORY 5 - Counter wird angezeigt und mit 0 initialisiert
-[] #24  STORY 6 - Registrierung Spieler.

**Comment by gery0815** [comment]
-[] #
